---
DatasetLocation: 
  local_folder: "E:/mvtec_anomaly_detection/"
  remote_folder: "/linux/perezramos/mvtec_anomaly_detection/"
  local_folder_laptop: "C:/Users/jorge/Pictures/mvtec_anomaly_detection/"

