wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709561722.19294
    t:
      1:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      - 80
      3:
      - 23
      4: 3.8.10
      5: 0.16.3
      8:
      - 3
      - 5
      - 9
      13: windows-amd64
